server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

ingester:
  max_block_duration: 5m
  trace_idle_period: 10s

compactor:
  compaction:
    block_retention: 48h

querier:
  frontend_worker:
    frontend_address: "tempo:9095"

storage:
  trace:
    backend: local
    local:
      path: "/tmp/tempo/traces"
    block:
      bloom_filter_false_positive: 0.05
    wal:
      path: "/tmp/tempo/wal"

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: "/tmp/tempo/generator"
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true